// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d22e2717-a3f5-4ad5-b6ed-8a4082cc477f";

const char SSID[]               = "CapitalNet Fibra (99224-9595)";    // Network SSID (name)
const char PASS[]               = "C@130215!!";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "k?Ih#Jbb#fi7tmZ72vQIZmyJx";    // Secret device password

void onChaleiraChange();

CloudSwitch chaleira;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(chaleira, READWRITE, ON_CHANGE, onChaleiraChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
